/**
 * OpenAI Section Component
 * Manages OpenAI API configuration and AI title generation
 */

import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { useOptimizely } from '../../../../hooks/useOptimizely';
import { API_URL } from '../../../../config';
import { ConfigData } from '../types';
import { trackConfigSettingsSaved } from '../../../../utils/analytics';
import { trackOptimizelyEvent, OPTIMIZELY_EVENTS, isFeatureBeingConfigured } from '../../../../utils/optimizelyTracking';
import { PasswordInput } from '../../PasswordInput';
import { error as logError } from '../../../../utils/logger';


interface OpenAISectionProps {
  config: ConfigData | null;
  originalConfig: ConfigData | null;
  setConfig: (config: ConfigData) => void;
  setOriginalConfig: (config: ConfigData) => void;
  savingSection: string | null;
  setSavingSection: (section: string | null) => void;
  setMessage: (message: { type: "success" | "error"; text: string }) => void;
  // Navigation
  scrollToOpenAI?: boolean;
  setScrollToOpenAI?: (value: boolean) => void;
  sectionRef?: React.RefObject<HTMLDivElement | null>;
}

const OpenAISection: React.FC<OpenAISectionProps> = ({
  config,
  originalConfig,
  setConfig,
  setOriginalConfig,
  savingSection,
  setSavingSection,
  setMessage,
  scrollToOpenAI,
  setScrollToOpenAI,
  sectionRef,
}) => {
  const { t } = useTranslation();
  const { optimizely } = useOptimizely();
  const openAISectionRef = useRef<HTMLDivElement>(null);
  const apiKeyInputRef = useRef<HTMLInputElement>(null);

  // Handle scrollToOpenAI trigger from parent
  useEffect(() => {
    if (scrollToOpenAI) {
      // Use the sectionRef if provided, otherwise use local openAISectionRef
      const refToUse = sectionRef?.current || openAISectionRef.current;
      if (refToUse) {
        const yOffset = -100; // Offset to account for header
        const y = refToUse.getBoundingClientRect().top + window.pageYOffset + yOffset;
        window.scrollTo({ top: y, behavior: 'smooth' });
        
        // Focus the API key input after scrolling
        setTimeout(() => {
          if (apiKeyInputRef.current) {
            apiKeyInputRef.current.focus();
          }
        }, 400);
      }
      // Reset the trigger
      if (setScrollToOpenAI) {
        setScrollToOpenAI(false);
      }
    }
  }, [scrollToOpenAI, setScrollToOpenAI, sectionRef]);

  // handleSetupOpenAI removed - handled by parent component now via URL params

  // Automatically disable auto-generate when API key is removed
  useEffect(() => {
    if (
      config &&
      !config.openai?.apiKey &&
      config.ai?.autoGenerateTitlesOnUpload
    ) {
      const newConfig = {
        ...config,
        ai: {
          ...config.ai,
          autoGenerateTitlesOnUpload: false,
        },
      };
      setConfig(newConfig);
    }
  }, [config?.openai?.apiKey]);

  const updateConfig = (path: string[], value: any) => {
    if (!config) return;

    const newConfig = { ...config };
    let current: any = newConfig;

    for (let i = 0; i < path.length - 1; i++) {
      current[path[i]] = { ...current[path[i]] };
      current = current[path[i]];
    }

    current[path[path.length - 1]] = value;
    setConfig(newConfig);
  };

  // Auto-save handler for AI toggle (like published toggle for albums)
  const handleToggleAutoAI = async () => {
    if (!config) return;

    // Don't allow toggling if no API key is set
    if (!config.openai?.apiKey) {
      setMessage({
        type: "error",
        text: t('openAI.apiKeyRequired'),
      });
      return;
    }

    const newValue = !(config.ai?.autoGenerateTitlesOnUpload || false);

    // Optimistically update UI
    const newConfig = {
      ...config,
      ai: {
        ...config.ai,
        autoGenerateTitlesOnUpload: newValue,
      },
    };
    setConfig(newConfig);

    try {
      const res = await fetch(`${API_URL}/api/config`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(newConfig),
      });

      if (res.ok) {
        // Update original config to match
        setOriginalConfig(structuredClone(newConfig));
        setMessage({
          type: "success",
          text: newValue ? t('openAI.autoGenerateEnabled') : t('openAI.autoGenerateDisabled'),
        });
      } else {
        const error = await res.json();
        setMessage({
          type: "error",
          text: error.error || t('openAI.failedToUpdate'),
        });
        // Revert on error
        setConfig(config);
      }
    } catch (err) {
      setMessage({ type: "error", text: t('common.networkError') });
      // Revert on error
      setConfig(config);
    }
  };

  // Validate OpenAI API key
  const validateOpenAIKey = async (apiKey: string): Promise<boolean> => {
    try {
      const response = await fetch(
        `${API_URL}/api/config/validate-openai-key`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          credentials: "include",
          body: JSON.stringify({ apiKey }),
        }
      );

      if (!response.ok) {
        return false;
      }

      const data = await response.json();
      return data.valid;
    } catch (err) {
      logError("Error validating OpenAI key:", err);
      return false;
    }
  };

  const handleSaveSection = async () => {
    if (!config) return;

    // Validate OpenAI API key before saving
    if (config.openai?.apiKey) {
      setSavingSection("OpenAI");

      const isValid = await validateOpenAIKey(config.openai.apiKey);

      if (!isValid) {
        setMessage({
          type: "error",
          text: t('openAI.invalidApiKey'),
        });
        setSavingSection(null);
        return;
      }
    }

    setSavingSection("OpenAI");

    try {
      const res = await fetch(`${API_URL}/api/config`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
        body: JSON.stringify(config),
      });

      if (res.ok) {
        // Track config settings save
        trackConfigSettingsSaved('OpenAI');
        
        // Track Optimizely event if OpenAI is being configured for the first time
        if (isFeatureBeingConfigured(config.openai?.apiKey, originalConfig?.openai?.apiKey)) {
          trackOptimizelyEvent(OPTIMIZELY_EVENTS.OPENAI_CONFIGURED, optimizely);
        }
        
        setMessage({ type: "success", text: t('settings.saved', { section: 'OpenAI' }) });
        // Update original config after successful save
        setOriginalConfig(structuredClone(config));
        // Dispatch event to notify OpenAI page
        window.dispatchEvent(new Event('openai-config-saved'));
      } else {
        const errorData = await res
          .json()
          .catch(() => ({ error: t('common.unknownError') }));
        setMessage({
          type: "error",
          text: errorData.error || t('settings.failedToSave'),
        });
      }
    } catch (err) {
      const errorMessage =
        err instanceof Error ? err.message : t('settings.errorSaving');
      setMessage({ type: "error", text: errorMessage });
      logError("Failed to save config:", err);
    } finally {
      setSavingSection(null);
    }
  };

  const hasUnsavedChanges = (): boolean => {
    if (!config || !originalConfig) return false;
    // Only check API key, not the auto-generate toggle (which auto-saves)
    return config.openai?.apiKey !== originalConfig.openai?.apiKey;
  };

  if (!config) return null;

  return (
    <div ref={sectionRef || openAISectionRef}>
      <div className="openai-settings-grid">
          {/* Left: API Key Section */}
          <div className="openai-section">
            <label className="openai-section-label">{t('openAI.apiKey')}</label>
            <PasswordInput
              inputRef={apiKeyInputRef}
              value={config.openai?.apiKey || ""}
              onChange={(e) =>
                updateConfig(["openai", "apiKey"], e.target.value)
              }
              className="branding-input"
              placeholder="sk-..."
            />

            {/* Save/Cancel buttons */}
            {hasUnsavedChanges() && (
              <div
                style={{
                  display: "flex",
                  gap: "0.5rem",
                  marginTop: "0.5rem",
                }}
              >
                <button
                  type="button"
                  onClick={handleSaveSection}
                  disabled={savingSection !== null}
                  className="btn-primary"
                  style={{ flex: 1 }}
                >
                  {savingSection === "OpenAI" ? t('common.saving') : t('common.save')}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setConfig(originalConfig!);
                  }}
                  disabled={savingSection !== null}
                  className="btn-secondary"
                  style={{ flex: 1 }}
                >
                  {t('common.cancel')}
                </button>
              </div>
            )}
          </div>

          {/* Right: Auto-generate Toggle Section */}
          <div className="openai-section">
            <label className="openai-section-label">
              {t('openAI.autoGenerateLabel')}
            </label>
            <div className="ai-toggle-container">
              <div className="ai-toggle-controls">
                <button
                  type="button"
                  onClick={handleToggleAutoAI}
                  disabled={!config.openai?.apiKey}
                  title={
                    !config.openai?.apiKey
                      ? t('openAI.apiKeyRequired')
                      : ""
                  }
                  className={`toggle-button ${
                    config.ai?.autoGenerateTitlesOnUpload ? "active" : ""
                  }`}
                  style={{
                    width: "48px",
                    height: "24px",
                    borderRadius: "12px",
                    border: "none",
                    cursor: config.openai?.apiKey
                      ? "pointer"
                      : "not-allowed",
                    position: "relative",
                    transition: "background-color 0.2s",
                    backgroundColor: config.ai?.autoGenerateTitlesOnUpload
                      ? "var(--primary-color)"
                      : "rgba(255, 255, 255, 0.1)",
                    opacity: config.openai?.apiKey ? 1 : 0.5,
                    flexShrink: 0,
                  }}
                >
                  <span
                    style={{
                      position: "absolute",
                      top: "2px",
                      left: config.ai?.autoGenerateTitlesOnUpload
                        ? "26px"
                        : "2px",
                      width: "20px",
                      height: "20px",
                      borderRadius: "50%",
                      backgroundColor: "white",
                      transition: "left 0.2s",
                      boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
                    }}
                  />
                </button>
                <span
                  style={{
                    color: config.ai?.autoGenerateTitlesOnUpload
                      ? "var(--primary-color)"
                      : "#888",
                    fontSize: "0.9rem",
                    fontWeight: 600,
                    opacity: config.openai?.apiKey ? 1 : 0.5,
                    flexShrink: 0,
                  }}
                >
                  {config.ai?.autoGenerateTitlesOnUpload
                    ? t('common.enabled')
                    : t('common.disabled')}
                </span>
              </div>
            </div>
            {!config.openai?.apiKey && (
              <p
                style={{
                  fontSize: "0.85rem",
                  color: "#fbbf24",
                  marginTop: "0.5rem",
                  marginBottom: 0,
                }}
              >
                ⚠️ {t('openAI.apiKeyRequiredWarning')}
              </p>
            )}
          </div>
        </div>
    </div>
  );
};

export default OpenAISection;
